## Optimization
### 2017.09.12

http://i-systems.github.io/HSE545/machine%20learning%20all/cvxpy_install/CVXPY%2BInstallation%2BGuide%2Bfor%2BWindows.html

Installation Guide for python 3.6 

In [1]:
import numpy as np
import cvxpy as cvx

In [2]:
f = np.array([1,1])
A = np.array([[2,1], [1,2]])
b = np.array([[29], [25]])
lb = np.array([[2], [5]])
ub = []

In [3]:
x = cvx.Variable(2,1)

obj = cvx.Minimize(-f * x)
const = [A*x <= b, lb <= x]

prob = cvx.Problem(obj, const)
prob.solve()

-17.999999998643816

In [4]:
x.value

matrix([[ 11.],
        [  7.]])

2017.09.14
Gradient Descent

In [5]:
from cvxpy import *

In [6]:
H = np.array([[2,0],[0,2]])
f = -np.array([[6],[6]])

In [10]:
# CVXPY

x = Variable(2,1)
obj = Minimize(1/2 * quad_form(x, H) + f.T * x)
const = []

prob = Problem(obj, const).solve()

In [11]:
x.value

matrix([[ 2.99996765],
        [ 2.99996765]])

In [17]:
# Gradient Descent

x = np.array([[1],[0]]) # intial point (random)
alpha = 0.2

for i in range(10):
    g = H.dot(x) + f
    x = x - alpha * g

print(x)

[[ 2.98790676]
 [ 2.98186015]]
