In [1]:
import numpy as np


A = np.array([[4, -5],
              [-2, 3]])
b = np.array([[-13],
              [9]])

x = np.linalg.inv(A).dot(b) # 행렬과 벡터의 내적
x

array([[ 3.],
       [ 5.]])

In [6]:
y = np.linalg.inv(A)*b # 행렬에 상수값 곱한 것

print(A); print(b); print(np.linalg.inv(A))
y

[[ 4 -5]
 [-2  3]]
[[-13]
 [  9]]
[[ 1.5  2.5]
 [ 1.   2. ]]


array([[-19.5, -32.5],
       [  9. ,  18. ]])

In [22]:
a = np.array([1,1]).reshape(-1,1)
b = np.array([1,1])

a = np.asmatrix(a)
b = np.asmatrix(b)

b.shape

(1, 2)